"""Validate Nexmon CSI extraction directly on a router, without Pi/MQTT access."""

import argparse
import os
import shlex
import sys

import paramiko


def run(client, command, timeout=30):
    _, stdout, stderr = client.exec_command(command, timeout=timeout)
    output = stdout.read().decode(errors="replace")
    error = stderr.read().decode(errors="replace")
    status = stdout.channel.recv_exit_status()
    return status, output, error


def build_parser():
    parser = argparse.ArgumentParser(
        description="Configure a fixed-channel CSI receiver and count CSI datagrams locally."
    )
    parser.add_argument("--host", default="192.168.48.5")
    parser.add_argument("--pi-host", help="Optional Pi SSH jump host")
    parser.add_argument("--username", default="wiloc")
    parser.add_argument("--channel", type=int, default=36)
    parser.add_argument("--bandwidth", type=int, choices=(20, 40, 80), default=80)
    parser.add_argument("--streams", type=int, choices=(1, 2, 3, 4), default=4)
    parser.add_argument("--mac", help="Optional single-source firmware MAC filter")
    parser.add_argument("--seconds", type=int, default=15)
    return parser


def build_setup_command(args):
    values = [
        "/jffs/csi/setup.sh",
        args.channel,
        args.bandwidth,
        args.streams,
    ]
    if args.mac:
        values.append(args.mac)
    return " ".join(shlex.quote(str(value)) for value in values)


def main():
    parser = build_parser()
    args = parser.parse_args()

    password = os.environ.get("WIRES_ROUTER_PASSWORD") or os.environ.get(
        "WIRES_PI_PASSWORD"
    )
    if not password:
        parser.error("set WIRES_ROUTER_PASSWORD or WIRES_PI_PASSWORD")

    setup = build_setup_command(args)
    # CSI generated by the patched firmware is emitted as UDP/5500 on the router.
    # Counting it here isolates RF extraction from Ethernet, Pi, and MQTT failures.
    # Do not use BusyBox ``timeout`` here: ASUSWRT versions disagree on its
    # syntax. Start tcpdump explicitly and stop exactly that process instead.
    capture = (
        "capture=/tmp/wiros-csi-probe.$$.log; "
        "errors=/tmp/wiros-csi-probe.$$.err; "
        "/jffs/csi/tcpdump -l -n -i any udp port 5500 "
        '>"$capture" 2>"$errors" & capture_pid=$!; '
        f"sleep {args.seconds}; "
        'kill "$capture_pid" 2>/dev/null || true; '
        'wait "$capture_pid" 2>/dev/null || true; '
        'wc -l < "$capture"; cat "$errors" >&2; '
        'rm -f "$capture" "$errors"'
    )

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    pi = None
    try:
        sock = None
        if args.pi_host:
            pi = paramiko.SSHClient()
            pi.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            pi.connect(
                args.pi_host,
                username=args.username,
                password=password,
                timeout=10,
            )
            sock = pi.get_transport().open_channel(
                "direct-tcpip", (args.host, 22), ("127.0.0.1", 0)
            )
        client.connect(
            args.host,
            username=args.username,
            password=password,
            sock=sock,
            timeout=10,
        )
        status, output, error = run(client, setup + " 2>&1", timeout=90)
        print("=== setup ===")
        print(output.strip())
        if error:
            print(error.strip(), file=sys.stderr)
        if status:
            raise RuntimeError(f"router CSI setup failed with status {status}")

        status, output, error = run(client, capture, timeout=args.seconds + 10)
        if status not in (0, 124):
            raise RuntimeError(
                f"router capture failed with status {status}: {output}{error}"
            )
        count = int(output.strip().splitlines()[-1])
        print("=== RF capture ===")
        print(f"host={args.host}")
        print(f"channel={args.channel} bandwidth_mhz={args.bandwidth}")
        print(f"mac_filter={args.mac or 'none (RPi allowlist)'}")
        print(f"duration_seconds={args.seconds}")
        print(f"csi_datagrams={count}")
        print(f"rate_hz={count / args.seconds:.2f}")
        if count == 0:
            print("result=NO_MATCHING_RF_FRAMES")
            return 2
        print("result=PASS")
        return 0
    finally:
        client.close()
        if pi is not None:
            pi.close()


if __name__ == "__main__":
    raise SystemExit(main())
